version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    groups:
      next:
        patterns:
          - next
          - eslint-config-next
      react:
        patterns:
          - react
          - react-dom
      types:
        patterns:
          - "@types/*"
    schedule:
      interval: daily
